# Example template of what I would use against machines - fill up how you prefer 

ungrouped:
  hosts:
    localhost:
webservers_spaceship:
  hosts:
    localhost:
    127.0.0.1:
dbservers:
  hosts:
    localhost:
    127.0.0.1:
    three.example.com:
hospital_database1:
  hosts:
    localhost:
    127.0.0.1:
hospital_database2:
  hosts:
    localhost:
    127.0.0.1:
prod_hospital:
  hosts:
    localhost:
    127.0.0.1:
test_hospital:
  hosts:
    localhost:
    127.0.0.1:
