---
- hosts: localhost
  tasks:
    - name: Update Ubuntu System
      become: true
      apt:
        upgrade: yes
        cache_valid_time: 5069

    - name: Install Rkhunter
      become: true
      apt: 
        name: rkhunter 

    - name: Install Tripwire
      become: true
      apt:
        name: rkhunter 

    - name: Install USBGuard 
      become: true
      apt:
        name: usbguard 

    - name: Install Crowdsec
      become: true
      apt:
        name: crowdsec 

    - name: Crowdsec Status Check
      service:
        name: crowdsec
        state: started
        enabled: yes 
    
    - name: UsbGuard Check
      service:
        name: usbguard
        state: started
        enabled: yes 

